### ISSUE TITLE
點名簿沒有正常運作  :bug

### ISSUE THREAD

**Issue by Civon** [pionxzh/eCourse-Plus-Plus#1]
如題，沒抓到資料
有想到再補充。

**Comment by pionxzh** [comment]
問題已確認並修正了
新版本也已推送上線
感謝回報🍺 

稍微說明一下原因:
在Course.changeCourse() 這個課程跳轉的function需要用到學年及學期
之前都是hardcode數值進去 換學期我就改一改推送上去
現在可以自己算了 不需要每次重新修改
