### ISSUE TITLE
PWA icon 在 ios 桌面上沒有滿版  :enhancement

### ISSUE THREAD

**Issue by Civon** [pionxzh/eCourse-Plus-Plus#2]
雖然我很懷疑有沒有人用PWA功能．．．

> 狀況： IOS(iphone, ipad)  桌面 ICON 會有白邊

>  建議：增加解析度，或是讓外圍深色範圍更大

**Comment by Civon** [comment]
Not sure its on purpose or not
https://github.com/pionxzh/eCourse-Plus-Plus/blob/master/static/apple-touch-icon.png

**Comment by pionxzh** [comment]
生成icon時沒有仔細檢查
已經重新上傳
thx
