### ISSUE TITLE
「授課大綱」, 「教師資訊」 button not show in narrow device   :bug

### ISSUE THREAD

**Issue by Civon** [pionxzh/eCourse-Plus-Plus#4]
as title, on android, IOS( imitation ) 
905a68d55333dfe9ad9c2cbe2b1c055ba6e5418a

**Comment by Civon** [comment]
nope, not fix yet
![image](https://user-images.githubusercontent.com/24861096/53298027-5ecdb200-3862-11e9-9fc0-9d38978fe237.png)

**Comment by pionxzh** [comment]
我還未更新上去

**Comment by Civon** [comment]
oh, i mistook
