### ISSUE TITLE
點名成績沒爬到  :bug

### ISSUE THREAD

**Issue by Civon** [pionxzh/eCourse-Plus-Plus#6]
As title, 
因 github  Partially Degraded Service 之後補圖

**Comment by Civon** [comment]
sor, 忘記之前開過，
不過好像沒有解決
![image](https://user-images.githubusercontent.com/24861096/53819041-1f127300-3fa4-11e9-8062-f724666f79f8.png)

**Comment by pionxzh** [comment]
跟之前的原因不一樣
主要是當時寫這部分是參考當時所選的幾堂課去測的
現在放寬了搜尋條件
應該老師欄目打什麼都可以抓出來了
當然後面不喜歡填出席/缺席的也沒辦法
